Repository markanthonymorales/good-food-recipe, pull requests merged in 2024-04, with the labels that each got.

#3 [Initilized] Final init (start project)
  .gitignore
  README.md
  package.json
  popup.html
  src/App.vue
  src/assets/Chrome-Logo.png
  src/assets/click-here.png
  src/assets/icons/icon128.png
  src/assets/icons/icon16.png
  src/assets/icons/icon48.png
  src/background.ts
  src/content-scripts/App.vue
  src/content-scripts/content.ts
  src/main.ts
  src/manifest.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: documentation, good first issue

#4 [Initilized] Folders structures
  src/composables/custom-common-composable-here.ts
  src/data-storage/example.panlasang-pinoy.json
  src/resources/panlasang-pinoy-routes.json
  src/types/resources-types-here.ts
  src/views/components/custom-common-components-here.vue
Labels: documentation, good first issue

#5 [Setup Page] Initialized route, create homepage, and about, setup com…
  .gitignore
  README.md
  package.json
  src/App.vue
  src/main.ts
  src/router/index.ts
  src/views/Aboutpage.vue
  src/views/Homepage.vue
  src/views/components/Loader.vue
  src/views/components/Navigation.vue
  src/views/components/custom-common-components-here.vue
Labels: enhancement

#7 [Rename] Rename package name and manifest name, change also icons
  package.json
  src/assets/icons/icon128.png
  src/assets/icons/icon16.png
  src/assets/icons/icon48.png
  src/manifest.json
Labels: good first issue

#8 [Setup Page] Initialized tailwind, postcss, and components
  package.json
  postcss.config.cjs
  src/assets/styles/app.css
  src/main.ts
  src/router/index.ts
  src/views/Aboutpage.vue
  src/views/Homepage.vue
  src/views/Listpage.vue
  src/views/Loginpage.vue
  src/views/components/Navigation.vue
  tailwind.config.cjs
Labels: good first issue

#10 [Fixed] Fixing navigation with logo, add search bar
  package.json
  src/assets/Logo.png
  src/views/Homepage.vue
  src/views/components/Navigation.vue
Labels: bug

#11 [Footer] Adding footer to all page
  src/assets/styles/app.css
  src/views/Aboutpage.vue
  src/views/Homepage.vue
  src/views/Listpage.vue
  src/views/Loginpage.vue
  src/views/components/FooterNav.vue
Labels: good first issue

#13 [Database] Database connector and list of recipe available
  json-module.d.ts
  package.json
  src/background.ts
  src/composables/custom-common-composable-here.ts
  src/composables/data-compiler.ts
  src/data-storage/database1.json
  src/data-storage/database2.json
  src/main.ts
  src/manifest.json
  src/router/index.ts
  src/views/Aboutpage.vue
  src/views/Adminpage.vue
  src/views/Homepage.vue
  src/views/Listpage.vue
  src/views/Loginpage.vue
  src/views/PrivacyPolicy.vue
  src/views/TermsConditions.vue
  src/views/components/FooterNav.vue
  tsconfig.json
Labels: bug

#14 [Feature] Creating Admin panel
  json-module.d.ts
  module.d.ts
  package.json
  src/composables/secret-key.ts
  src/resources/secret.json
  src/router/index.ts
  src/views/Adminpage.vue
  src/views/Homepage.vue
  src/views/Loginpage.vue
  src/views/components/Navigation.vue
  tsconfig.json
Labels: enhancement

#15 [DB] add dexis as indexDb for DB, initialized db and tables recipes, …
  package.json
  src/background.ts
  src/composables/db.ts
  src/composables/secret-key.ts
  src/main.ts
  src/resources/panlasang-pinoy-routes.json
  src/types/recipes-type.ts
  src/types/resources-types-here.ts
  src/types/source-type.ts
  src/views/Adminpage.vue
  src/views/Homepage.vue
  src/views/Listpage.vue
Labels: bug, enhancement

#16 [FEATURE] Scrapper init, add DB, add Admin Func
  package.json
  src/background.ts
  src/composables/data-compiler.ts
  src/composables/db.ts
  src/composables/scrapper.ts
  src/data-storage/database1.json
  src/data-storage/database2.json
  src/data/source-data.json
  src/types/source-type.ts
  src/views/Adminpage.vue
Labels: bug, enhancement

#17 [BUGFIX] Fixing admin
  src/views/Adminpage.vue
Labels: bug

#19 Develop
  src/composables/scrapper.ts
  src/views/Adminpage.vue
Labels: bug

#20 [BUGFIX] Add limit call if empty on scrapper
  src/views/Homepage.vue
Labels: bug

#21 [feat] added scrapping for notes
  src/composables/scrapper.ts
Labels: bug, enhancement

#22 Feature/scrapper
  src/composables/scrapper.ts
Labels: bug, enhancement

#23 Develop
  src/background.ts
  src/composables/insert-new-recipe.ts
  src/composables/scrapper.ts
  src/composables/site-map-scrapper.ts
  src/data/source-data.json
  src/manifest.json
  src/router/index.ts
  src/views/Adminpage.vue
  src/views/Homepage.vue
  src/views/Listpage.vue
  src/views/Loginpage.vue
  src/views/SitemapScrapper.vue
  src/views/components/FooterNav.vue
  src/views/components/Navigation.vue
Labels: bug, enhancement

#24 [FEATURE] Display recipe, search scrap, home, list
  src/composables/insert-new-recipe.ts
  src/composables/scrapper.ts
  src/composables/search-scrapper.ts
  src/router/index.ts
  src/views/Homepage.vue
  src/views/Listpage.vue
  src/views/Recipepage.vue
Labels: bug, enhancement
